[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "qailo"
version = "0.1.0"
description = "Quantum Circuit Examples"
authors = [
    { name = "Synge Todo", email = "wistaria@phys.s.u-tokyo.ac.jp" },
]
classifiers = [
    "License :: Apache-2.0",
]

[project.urls]
Homepage = "https://github.com/wistaria/qailo"

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "0.4"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"
